[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  port = 3999
  targetPort = 3002
  functionsPort = 8888

[functions."daily-digest"]
  schedule = "@daily"

# Dynamic sitemap routes
[[redirects]]
  from = "/sitemap-*.xml"
  to = "/.netlify/functions/dynamic-sitemap/:splat"
  status = 200

# Main sitemap index
[[redirects]]
  from = "/sitemap_index.xml"
  to = "/.netlify/functions/dynamic-sitemap"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Category landing pages
[[redirects]]
  from = "/lists/:category"
  to = "/search?category=:category"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
